databases:
  - name: calendar-api
    databaseName: calendar_api
    user: calendar_api

services:
  - type: web
    name: calendar-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn calendar-api.wsgi:application"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: calendar-api
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4